"""
Satellite imagery gives us numpy arrays and NVDI floats.
GDLET gives us event codes, tone scores, and article counts.
Procurement gives us contract amounts, vendor names and categories.

These three sources speak completely different languages. if langGraph were to understand all three formats simultaneously, it would need three seperate code paths, three seperate reasoning strategies and three seperate validation logic. Adding a fourth source would require rewriting a large part of the agent.

SOLUTION:
Every Source reguardless of origin produces exactly one typr of object: 
an AnamolyEvent. The agent dosent care if this event id from satellite, a news article, or a government contract.

This is the main function of narmalization, and its what makes the system extensible.
Want to add foruth source? Write one ingestion script that creates an anamolyEvent object form it. The entire rest of the system works unchanged.
"""

from __future__ import annotations
import string
import uuid
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from typing import Any

"""
─────────────────────────────────────────────
ENUMERATIONS
Enums enforce that a field can only hold one of a fixed set of values.
Using an enum instead of a raw string like "satellite" means a typo
like "satelite" is a crash at startup, not a silent bug at 2 AM.
─────────────────────────────────────────────
"""

class AnomalySource(str,Enum):
    """
    Which data pipeline detected this anomaly??
    
    We inherit from both str and Enum so that AnomalySource.SATELLITE
    behaves like the string "SATELLITE" everywhere strings are expected
    (JSON serialization, database storage, API responses) without
    needing explicit conversion.
    """
    SATELLITE   = "SATELLITE"
    GDELT       = "GDELT"
    PROCUREMENT = "PROCUREMENT"
    
class BriefStatus(str,Enum):
    """
    Lifecycle stage of an investigation brief.
    DRAFT -> Generated by agent, not yey seen by human.
    REVIEWED -> Human has seen it and added notes
    PUBLISHED -> Verified and approved for external sharing.
    """
    DRAFT="DRAFT"
    REVIEWED="REVIEWED"
    PUBLISHED="PUBLISHED"
    
class ConfidenceTier(str,Enum):
    """
    Human readeable confidence level give by LLM .
    """
    LOW="LOW"
    MEDIUM="MEDIUM"
    HIGH="HIGH"
    
class SignalType(str,Enum):
    """
    What kind of anomaly was detected?
 
    Satellite signals:
      LAND_COVER_CHANGE   → Significant pixel-level change between two dates
      VEGETATION_LOSS     → NDVI drop indicating deforestation or burning
      THERMAL_ANOMALY     → Unusual heat signature (fires, industrial activity)
      STRUCTURE_CHANGE    → New structures appearing or existing ones demolished
 
    GDELT signals:
      TONE_CRASH          → Sudden shift to very negative news sentiment
      VOLUME_SPIKE        → Unusually high news coverage volume
      COMMUNICATION_BLACKOUT → Sudden near-absence of coverage (suppression signal)
      CONFLICT_EVENTS     → Spike in CAMEO conflict/violence event codes
 
    Procurement signals:
      SPEND_SPIKE         → Unusually high spend in a category vs. baseline
      NEW_VENDOR_PATTERN  → New supplier appearing in sensitive categories
      EMERGENCY_CONTRACT  → Contract flagged as emergency/direct-award type
      CATEGORY_SHIFT      → Unusual mix of procurement categories
    """
    # Satellite
    LAND_COVER_CHANGE="LAND_COVER_CHANGE"
    VEGETATION_LOSS="VEGETATION_LOSS"
    THERMAL_ANOMALY="THERMAL_ANOMALY"
    STRUCTURE_CHANGE="STRUCTURE_CHANGE"
    
    # GDELT
    TONE_CRASH='TONE_CRASH'
    VOLUME_SPIKE="VOLUME_SPIKE"
    COMMUNICATION_BLACKOUT="COMMUNICATION_BLACKOUT"
    CONFLICT_EVENTS="CONFLICT_EVENTS"
    
    # PROCUREMENT details
    SPEND_SPIKE='SPEND_SPIKE'
    NEW_VENDOR_PATTERN="NEW_VENDOR_PATTERN"
    EMERGENCY_CONTACT='EMERGENCY_CONTACT'
    CATEGORY_SHIFT='CATEGORY_SHIFT'
    
@dataclass
class AnomalyEvent:
    """
    A single detected anomaly from any data source.
    
    The fields are structered form most to least important 
    The top fields are mostly populated the bottom fields hold source specific info
    """
    
    # ------- Identifiers -------
    event_id:str
    source:AnomalySource
    region_id:str
    
    # ------- Geography -------
    country_code:str
    lat:float
    lng:float
    
    #  ----- Timing -------
    # When the anomaly occured not when it was detected. Stored in UTC format.
    timestamp:datetime
    
    # ------- SIgnal type ------
    # What kind of anomaly was detected.
    signal_type:SignalType
    # 0.0 barely anomaly, 1.0 maximally anomalous
    # (e.g., a z-score of 4.2 or a change score of 0.78) into this 0–1 range.
    # Normalization formula and calibration documented in METHODOLOGY.md
    intensity_score:float
    
    
    # ------ Raw Data ------
    # The unmodified source data that produced this event.
    # For satellite: {'ndvi_before': 0.72, 'ndvi_after': 0.31, 'change_score': 0.65,
    #                 'tile_path_before': '...', 'tile_path_after': '...'}
    # For GDELT:     {'tone_mean': -4.2, 'volume_7d_avg': 12.3, 'zscore': -3.1,
    #                 'top_cameo_codes': ['193', '194'], 'sample_articles': [...]}
    # For procurement: {'contract_id': '...', 'amount_usd': 4200000,
    #                   'category': 'MILITARY', 'vendor': '...', 'zscore': 3.4}
    raw_data:dict[str,Any]=field(default_factory=dict)
    
    # Additional context that's useful but doesn't fit the core schema.
    # For satellite: {'cloud_cover_pct': 12, 'resolution_m': 10, 'satellite': 'S2A'}
    # For GDELT:     {'dominant_themes': ['MILITARY', 'DISPLACEMENT'], 'lang_count': 4}
    # For procurement: {'buyer_name': '...', 'award_date': '2024-03-15'}
    metadata:dict[str,Any]=field(default_factory=dict)
    
    # When our pipeline detected this, for audit purposes
    detected_at:datetime=field(default_factory=lambda: datetime.now(timezone.utc))
    
    def __post_init__(self):
        self._validate()
    
    def _validate(self):
        """
        Validate all field constraints. Raises value error with descriptive msg on any voilation        
        """    
        if not self.event_id:
            raise ValueError("event_id cannot be empty")
 
        if not (-90 <= self.lat <= 90):
            raise ValueError(f"lat must be between -90 and 90, got {self.lat}")
 
        if not (-180 <= self.lng <= 180):
            raise ValueError(f"lng must be between -180 and 180, got {self.lng}")
 
        if not (0.0 <= self.intensity_score <= 1.0):
            raise ValueError(
                f"intensity_score must be between 0.0 and 1.0, got {self.intensity_score}"
            )
 
        if len(self.country_code) != 2:
            raise ValueError(
                f"country_code must be 2 characters (ISO 3166-1 alpha-2), got '{self.country_code}'"
            )
 
        if not self.region_id:
            raise ValueError("region_id cannot be empty")
 
        # Ensure timestamps are timezone-aware (UTC). Naive datetimes cause
        # subtle bugs when comparing across timezones.
        if self.timestamp.tzinfo is None:
            raise ValueError(
                "timestamp must be timezone-aware. Use datetime.now(timezone.utc) "
                "or datetime(..., tzinfo=timezone.utc)"
            )
    def to_dict(self) -> dict[str, Any]:
        """
        Converts the event to a plain dict suitable for JSON serialization
        or database insertion.
 
        Handles the tricky parts automatically:
        - Enums → their string values ("SATELLITE", not "<AnomalySource.SATELLITE: 'SATELLITE'>")
        - Datetimes → ISO 8601 strings ("2024-03-15T14:22:00+00:00")
        """
        d=asdict(self)
        d['source']=self.source.value
        d['signal_type']=self.signal_type.value
        d['timestamp']=self.timestamp.isoformat()
        d['detected_at']=self.detected_at.isoformat()
        
        return d

        
    def to_json(self)->str:
        """Serializes to json string. Useful for logging and msg queues"""
        return json.dumps(self.to_dict(),ensure_ascii=False)
        
    @classmethod
    def from_dict(cls,data:dict[str,Any])->"AnomalyEvent":
        """
        reconstructs anomaly event from a dict. Handles the inverse of to_dict conversions:
        - String "SATELLITE" -> AnomalySource.SATELLITE
        - ISO 8601 string -> datetime with timezone
        """
        data=data.copy()
        #  COnverting string to enum
        data['source']=AnomalySource(data['source'])
        data['signal_type']=SignalType(data['signal_type'])
        
        # COnverting ISO string -> datetime
        # fromisoformat handles both "2024-03-15T14:22:00+00:00" and "2024-03-15T14:22:00Z"
        if isinstance(data['timestamp'],str):
            data['timestamp']=datetime.fromisoformat(data['timestamp'].replace('Z',"+00:00"))
        if isinstance(data.get('detected_at'),str):
            data['detected_at']=datetime.fromisoformat(data['detected_at'].replace('Z',"+00:00"))
        
        return cls(**data)    
    
    @classmethod 
    def from_json(cls, json_str: str) -> "AnomalyEvent":
        """Deserializes from a JSON string."""
        return cls.from_dict(json.loads(json_str))        
     
    # ------ FACTORY METHODS ------
    # Pre-configured constructors for each source type.
    # These set source-appropriate defaults so ingestion scripts don't
    # have to repeat boilerplate.
 
    @classmethod
    def make_satellite_event(
        cls,
        region_id: str,
        country_code: str,
        lat: float,
        lng: float,
        timestamp: datetime,
        signal_type: SignalType,
        intensity_score: float,
        raw_data: dict[str, Any] = None,
        metadata: dict[str, Any] = None,
    ) -> "AnomalyEvent":
        """Factory for satellite-sourced events with auto-generated UUID."""
        return cls(
            event_id=str(uuid.uuid4()),
            source=AnomalySource.SATELLITE,
            region_id=region_id,
            country_code=country_code,
            lat=lat,
            lng=lng,
            timestamp=timestamp,
            signal_type=signal_type,
            intensity_score=intensity_score,
            raw_data=raw_data or {},
            metadata=metadata or {},
        )
 
    @classmethod
    def make_gdelt_event(
        cls,
        region_id: str,
        country_code: str,
        lat: float,
        lng: float,
        timestamp: datetime,
        signal_type: SignalType,
        intensity_score: float,
        raw_data: dict[str, Any] = None,
        metadata: dict[str, Any] = None,
    ) -> "AnomalyEvent":
        """Factory for GDELT-sourced events."""
        return cls(
            event_id=str(uuid.uuid4()),
            source=AnomalySource.GDELT,
            region_id=region_id,
            country_code=country_code,
            lat=lat,
            lng=lng,
            timestamp=timestamp,
            signal_type=signal_type,
            intensity_score=intensity_score,
            raw_data=raw_data or {},
            metadata=metadata or {},
        )
 
    @classmethod
    def make_procurement_event(
        cls,
        region_id: str,
        country_code: str,
        lat: float,
        lng: float,
        timestamp: datetime,
        signal_type: SignalType,
        intensity_score: float,
        raw_data: dict[str, Any] = None,
        metadata: dict[str, Any] = None,
    ) -> "AnomalyEvent":
        """Factory for procurement-sourced events."""
        return cls(
            event_id=str(uuid.uuid4()),
            source=AnomalySource.PROCUREMENT,
            region_id=region_id,
            country_code=country_code,
            lat=lat,
            lng=lng,
            timestamp=timestamp,
            signal_type=signal_type,
            intensity_score=intensity_score,
            raw_data=raw_data or {},
            metadata=metadata or {},
        )
 
    
    # ------ DISPLAY ------
    def __repr__(self) -> str:
        return (
            f"AnomalyEvent("
            f"source={self.source.value}, "
            f"region={self.region_id}, "
            f"signal={self.signal_type.value}, "
            f"intensity={self.intensity_score:.2f}, "
            f"ts={self.timestamp.date()}"
            f")"
        )
 
 

# ------ INVESTIGATION BRIEF ------

# The output of the LangGraph agent. Produced only when the convergence scorer decides that a cluster of anomaly events is significant enough to warrant human attention.

 
@dataclass
class InvestigationBrief:
    """
    A structured query from the AI agent after successfully detecting convergent anomalities among different data sources
    
    This is final output of agent. This is what the user will read as output.
    
    It is a investigation summary not a verdict. It is designed to detect anomalies and alert not to give final answers. It is the starting point for human investigation not the end point.
    """
    
    # ------Identity------
    brief_id:str
    region_id:str
    
    # ------time window------
    # The time peroid when the events occured
    time_window_start:datetime
    time_window_end:datetime
    
    # ------Assessment------
    confidence_score:float
    confidence_tier:ConfidenceTier
    
    # ------ Souurce -------
    contributing_streams:list[str]
    
    # ------Evidence------
    # Structure example:
    # {
    #   "SATELLITE": {
    #     "events": [...],             # serialized AnomalyEvents
    #     "change_score_max": 0.73,
    #     "tile_path_before": "...",
    #     "tile_path_after": "...",
    #     "summary": "Significant land cover change detected..."
    #   },
    #   "GDELT": {
    #     "events": [...],
    #     "tone_zscore_min": -3.4,
    #     "volume_zscore_max": 2.8,
    #     "top_themes": ["193", "MILITARY"],
    #     "summary": "News sentiment collapsed to extreme negative..."
    #   },
    #   "PROCUREMENT": {
    #     "events": [...],
    #     "spend_zscore_max": 4.1,
    #     "categories": ["MILITARY", "MEDICAL"],
    #     "summary": "Anomalous procurement spend in military category..."
    #   }
    # }
    evidence:dict[str,Any]=field(default_factory=dict)
    
    
    # ----- Agent Reasoning ------
    # The full text generated by the LLM reasoning node.
    # Structured sections (enforced via prompt):
    #   1. What each stream found
    #   2. Why the convergence is significant
    #   3. Historical context from memory
    #   4. Confidence tier with explicit reasoning
    #   5. What a human investigator should look for next
    #   6. What the system cannot conclude and why
    agent_reasoning:str=""
    
    # Historical context retrieved from ChromaDB vector memory
    # Summarizes similar past cases from the same region
    historical_context:str=""
    
    # ------ Lifecycle ------    
    status:                 BriefStatus = BriefStatus.DRAFT
    reviewer_notes:         str = ""
    created_at:             datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at:             datetime = field(default_factory=lambda: datetime.now(timezone.utc)) 
    
    def __post_init__(self):
        self._validate()
 
    def _validate(self):
        if not self.brief_id:
            raise ValueError("brief_id cannot be empty")
 
        if not (0.0 <= self.confidence_score <= 1.0):
            raise ValueError(
                f"confidence_score must be between 0.0 and 1.0, got {self.confidence_score}"
            )
 
        if not self.contributing_streams:
            raise ValueError("contributing_streams cannot be empty")
 
        valid_sources = {s.value for s in AnomalySource}
        for stream in self.contributing_streams:
            if stream not in valid_sources:
                raise ValueError(
                    f"contributing_streams contains unknown source '{stream}'. "
                    f"Valid values: {valid_sources}"
                )
 
        # Check timezone-awareness FIRST — comparing naive vs aware datetimes
        # raises a TypeError, so we must validate tz before the ordering check.
        if self.time_window_start.tzinfo is None or self.time_window_end.tzinfo is None:
            raise ValueError("time_window datetimes must be timezone-aware (UTC)")
 
        if self.time_window_start >= self.time_window_end:
            raise ValueError("time_window_start must be before time_window_end")
 
    # --------COMPUTED PROPERTIES--------   
    @property
    def stream_count(self)->int:
        """How many independent sources contributed"""
        return len(set(self.contributing_streams))
    
    @property
    def is_multi_source(self) -> bool:
        """True if more than one data source contributed."""
        return self.stream_count > 1
 
    @property
    def duration_days(self) -> int:
        """Length of the time window covered by this brief, in days."""
        delta = self.time_window_end - self.time_window_start
        return delta.days
    
    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["confidence_tier"]      = self.confidence_tier.value
        d["status"]               = self.status.value
        d["time_window_start"]    = self.time_window_start.isoformat()
        d["time_window_end"]      = self.time_window_end.isoformat()
        d["created_at"]           = self.created_at.isoformat()
        d["updated_at"]           = self.updated_at.isoformat()
        return d
 
    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)
    
    
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "InvestigationBrief":
        data = data.copy()
        data["confidence_tier"] = ConfidenceTier(data["confidence_tier"])
        data["status"]          = BriefStatus(data["status"])
 
        for dt_field in ["time_window_start", "time_window_end", "created_at", "updated_at"]:
            if isinstance(data.get(dt_field), str):
                data[dt_field] = datetime.fromisoformat(
                    data[dt_field].replace("Z", "+00:00")
                )
        return cls(**data)
 
    @classmethod
    def from_json(cls, json_str: str) -> "InvestigationBrief":
        return cls.from_dict(json.loads(json_str))
 
    
    # ------ DISPLAY ------ 
    def summary_line(self) -> str:
        """One-line summary for logs and CLI output."""
        streams = "+".join(sorted(set(self.contributing_streams)))
        return (
            f"[{self.confidence_tier.value}] {self.region_id} | "
            f"{self.time_window_start.date()} → {self.time_window_end.date()} | "
            f"{streams} | score={self.confidence_score:.2f} | {self.status.value}"
        )
 
    def __repr__(self) -> str:
        return (
            f"InvestigationBrief("
            f"region={self.region_id}, "
            f"tier={self.confidence_tier.value}, "
            f"streams={self.stream_count}, "
            f"status={self.status.value}"
            f")"
        )